export const USER_TYPES = {
  ADMINISTRATOR: 0,
  USER: 1,
  ENTERTAINER: 2,
  BAND_MEMBER: 3,
  UNKNOWN: 999,
};

export const TRANSACTION_STATUSES = {
  FAILED: 'failed',
  SUCCESS: 'success',
  ABANDONED: 'abandoned',
};

export const RATINGS = {
  UPPER_BOUND: 5,
  LOWER_BOUND: 0,
};

export const NOTIFICATIONS = {
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  BID_APPROVED: 'BID_APPROVED',
  NEW_AWARD: 'NEW_AWARD',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_MADE: 'PAYMENT_MADE', // NOT SURE WHERE TO PUT THIS
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED', // PENDING FOR ADMIN
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED', // PENDING
  REQUEST_REJECTED: 'REQUEST_REJECTED', // PENDING
  REQUEST_INCREMENT: 'REQUEST_INCREMENT', // PENDING
};

export const NOTIFICATION_TYPE = {
  DANGER: 0, // RED
  CONTENT: 1, //AMBER
  INFO: 2, //  BLUE
  SUCCESS: 3, // GREEN
};

export const REQUEST_ACTION = {
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
  INCREMENT: 'Increment',
};
