import applicationRoutes from './applicationRoute';
import approveCommentRoutes from './approveCommentRoutes';
import bankDetailsRoutes from './bankDetailRoutes';
import commissionRoutes from './commissionRoute';
import contactRoutes from './contactRoutes';
import emailRoutes from './emailRoutes';
import entertainerRoutes from './entertainerRoutes';
import bandMemberRoutes from './bandMemberRoutes';
import eventEntertainerRoutes from './eventEntertainerRoute';
import eventRoutes from './eventRoutes';
import galleryRoutes from './galleryRoutes';
import globalNotificationRoutes from './globalNotificationRoutes';
import identificationRoutes from './identificationRoutes';
import imageRoutes from './imageRoutes';
import otherRoutes from './otherRoutes';
import paymentRoutes from './paymentRoute';
import ratingRoutes from './ratingRoute';
import reviewRoutes from './reviewRoutes';
import userRoutes from './userRoutes';
import videoRoutes from './videoRoutes';
import badgeRoutes from './badgeRoutes';
import welcomeRoute from './welcomeRoute';
import publicEventRoutes from './publicEventRoutes';
import adminRoute from './adminRoute';
import cronRoutes from './cronRoute';
import cancelEventEntertainerRoutes from './cancelEventEntertainerRoute';

const routes = (app) => {
  adminRoute(app);
  applicationRoutes(app);
  approveCommentRoutes(app);
  badgeRoutes(app);
  bandMemberRoutes(app);
  bankDetailsRoutes(app);
  cancelEventEntertainerRoutes(app);
  commissionRoutes(app);
  contactRoutes(app);
  cronRoutes(app);
  emailRoutes(app);
  entertainerRoutes(app);
  eventEntertainerRoutes(app);
  eventRoutes(app);
  galleryRoutes(app);
  globalNotificationRoutes(app);
  identificationRoutes(app);
  imageRoutes(app);
  otherRoutes(app);
  paymentRoutes(app);
  publicEventRoutes(app);
  ratingRoutes(app);
  reviewRoutes(app);
  userRoutes(app);
  videoRoutes(app);
  welcomeRoute(app);
};

export default routes;
